version: '3.9'

services:
    chatgpt-slackbot:
        image: chatgpt-slackbot
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "7779:7779"
        restart: always